; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.9 on Tue Dec 01 2020 17:25:16 GMT-0600 (Central Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


