; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.1.9 on Tue Dec 01 2020 17:25:16 GMT-0600 (Central Standard Time)
M280 P0 S90 ; retract BLTouch

