; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.9 on Tue Dec 01 2020 17:25:17 GMT-0600 (Central Standard Time)
; Wait for set temperatures to be reached
M116 P0

